communitycommit/config/routes.rb
Rails.application.routes.draw do

  resources :questionary_results
  resources :questionary_choices
  resources :questionary_items
  resources :questionaries
  
  get 'questionary_results/calc/:id', to: 'questionary_results#calc'
  get 'questionary_choices/new/:id', to: 'questionary_choices#new'
  get 'questionary_items/new/:id', to: 'questionary_items#new'
  post 'questionaries/:id', to: 'questionaries#sendform'
  
  get 'users/index'
  get 'users/show'
  get 'users/edit'
  get 'communities/index'
  get 'communities/show'
  get 'communities/new'
  get 'communities/edit'

root to: 'homes#top'

devise_for :admins, controllers: {
sessions:      'admins/sessions',
passwords:     'admins/passwords',
registrations: 'admins/registrations'
}
get "communities/belonged" => "communities#belonged"

namespace :admins do
 resources :users, :only => [:show]
 resources :communities do
  resources :posts do
   resources :post_comments, only: [:show, :index]
  end
 end
end

devise_for :users, controllers: {
  sessions:      'users/sessions',
  passwords:     'users/passwords',
  registrations: 'users/registrations'
}
namespace :users do
resources :users ,:only => [:show, :edit,:update]  
get '/search', to: 'search#search'
resources :communities, :only => [:index,:show] do
 resource :belongs, only: [:create, :destroy]
 resources :posts, :only => [:index,:show] do
   resources :post_comments, only: [:create, :destroy]
 end
end
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

communitycommit/app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
has_many :communities, dependent: :destroy 
has_many :posts, dependent: :destroy

end

communitycommit/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

communitycommit/app/models/belong.rb
class Belong < ApplicationRecord
    
belongs_to :user
belongs_to :community
    
end

communitycommit/app/models/community.rb
class Community < ApplicationRecord
    
belongs_to :admin
has_many :posts, dependent: :destroy
has_many :belongs, dependent: :destroy
has_many :questionaries, dependent: :destroy
   
  validates :name, presence: true
   
  def belonged_by?(user)
    belongs.where(user_id: user.id).exists?
  end

  def self.search_for(content, method)
    if method == 'perfect'
      Community.where(name: content)
    else
      Community.where('name LIKE ?', '%'+content+'%')
    end
  end

end

communitycommit/app/models/post.rb
class Post < ApplicationRecord
    
belongs_to :admin
belongs_to :community
has_many :post_comments, dependent: :destroy

validates :title, presence: true
validates :in_front, inclusion: { in: [true, false] }
attachment :image

end

communitycommit/app/models/post_comment.rb
class PostComment < ApplicationRecord
    
  belongs_to :user
  belongs_to :post

end

communitycommit/app/models/questionary.rb
class Questionary < ApplicationRecord
    
belongs_to :community
has_many :questionary_item
has_many :questionary_result

validates :title, :description, :deadline, presence: {message:"は、必須項目です。"}
    
end

communitycommit/app/models/questionary_choice.rb
class QuestionaryChoice < ApplicationRecord
    

belongs_to :questionary_item

validates :content, :value, presence: {message:"は、必須項目です。"}
validates :value, numericality: {message:"は、数字で入力してください。"}        
    
end

communitycommit/app/models/questionary_item.rb
class QuestionaryItem < ApplicationRecord
    

belongs_to :questionary
has_many :questionary_choice

validates :content, presence: {message:"は、必須項目です。"}
    
end

communitycommit/app/models/questionary_result.rb
class QuestionaryResult < ApplicationRecord
    

belongs_to :questionary

validates:result, presence: {message:"は、必須項目です。"}

end

communitycommit/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  validates :name, presence: true
  validates :email, presence: true

  has_many :communities
  has_many :post_comments, dependent: :destroy
  has_many :belongs, dependent: :destroy
end

communitycommit/app/controllers/homes_controller.rb
class HomesController < ApplicationController

def top
end

end

communitycommit/app/controllers/questionary_items_controller.rb
class QuestionaryItemsController < ApplicationController
  before_action :set_questionary_item, only: %i[ show edit update destroy ]

  # GET /questionary_items or /questionary_items.json
  def index
    @questionary_items = QuestionaryItem.all
  end
  # GET /questionary_items/new
  def new
    @questionary_item = QuestionaryItem.new
    @questionary_item.questionary_id = params[:id]
    @questinary = Questionary.find params[:id]
  end

  # POST /questionary_items or /questionary_items.json
  def create
    @questionary_item = QuestionaryItem.new(questionary_item_params)

    respond_to do |format|
      if @questionary_item.save
        format.html { redirect_to '/questionary_choices/new/' + @questionary_item.id.to_s }
        format.json { render :show, status: :created, location: @questionary_item }
      else
        format.html { redirect_to request.referer}
        format.json { render json: @questionary_item.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_questionary_item
      @questionary_item = QuestionaryItem.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def questionary_item_params
      params.require(:questionary_item).permit(:content, :questionary_id, :community_id)
    end
end

communitycommit/app/helpers/application_helper.rb
module ApplicationHelper
end

communitycommit/app/helpers/belongs_helper.rb
module BelongsHelper
end

communitycommit/app/helpers/communities_helper.rb
module CommunitiesHelper
end

communitycommit/app/helpers/homes_helper.rb
module HomesHelper
end

communitycommit/app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

communitycommit/app/helpers/post_helper.rb
module PostHelper
end

communitycommit/app/helpers/questionaries_helper.rb
module QuestionariesHelper
end

communitycommit/app/helpers/questionary_items_helper.rb
module QuestionaryItemsHelper
end

communitycommit/app/helpers/search_helper.rb
module SearchHelper
end

communitycommit/app/helpers/users_helper.rb
module UsersHelper
end

communitycommit/app/views/questionary_items/_form.html.erb
<%= form_with(model: questionary_item, local: true) do |form| %>
  <% if questionary_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(questionary_item.errors.count, "error") %> prohibited this questionary_item from being saved:</h2>

      <ul>
      <% questionary_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class= "questionary-field">
※このアンケート識別番号は<%= form.number_field :questionary_id %>です。
この数字は変更しないでください。</div>


  <div class="row mt-3">
  　<div class="col">
    <div class= "questionary-label"><%= form.label :"質問内容" %>  </div>
    <div class= "questionary-field"><%= form.text_area :content, :size=>"70" %>  </div>
  </div>
</div>

  <div class="row mt-2">
  　<div class="col">
    <%= form.submit :"選択肢を作成する" %>
  </div>
</div>
<% end %>

communitycommit/app/views/questionary_items/edit.html.erb
<h1>Editing Questionary Item</h1>

<%= render 'form', questionary_item: @questionary_item %>

<%= link_to 'Show', @questionary_item %> |
<%= link_to 'Back', questionary_items_path %>

communitycommit/app/views/questionary_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Questionary Items</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Questinary</th>
      <th>Community</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questionary_items.each do |questionary_item| %>
      <tr>
        <td><%= questionary_item.content %></td>
        <td><%= questionary_item.questinary_id %></td>
        <td><%= questionary_item.community_id %></td>
        <td><%= link_to 'Show', questionary_item %></td>
        <td><%= link_to 'Edit', edit_questionary_item_path(questionary_item) %></td>
        <td><%= link_to 'Destroy', questionary_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Questionary Item', new_questionary_item_path %>

communitycommit/app/views/questionary_items/new.html.erb
<h2 class="mb-3">質問の作成</h2>
<div>
アンケートの質問を１つずつ作成できます。
『質問内容』を作成したら、『選択肢を作成する』ボタンをクリックして、選択肢を作成してください。
</div>

<%= render 'form', questionary_item: @questionary_item %>

<div class="mt-3">
選択肢を作成が終了したら、『アンケートを完成する』ボタンを押して、アンケートが完成します。</br>
まだ、質問を加えたい場合は、『質問内容』を入力して、同様に選択肢を作成してください。</br>
アンケートの質問は20個まで作成できます。
</div>


<%= link_to 'アンケートを完成する', questionary_path(questionary_id: @questionary_id), class: 'btn btn-success m-3' %>

communitycommit/app/views/questionary_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @questionary_item.content %>
</p>

<p>
  <strong>Questinary:</strong>
  <%= @questionary_item.questinary_id %>
</p>

<p>
  <strong>Community:</strong>
  <%= @questionary_item.community_id %>
</p>

<%= link_to 'Edit', edit_questionary_item_path(@questionary_item) %> |
<%= link_to 'Back', questionary_items_path %>