communitycommit/config/routes.rb
Rails.application.routes.draw do

  resources :questionary_results
  resources :questionary_choices
  resources :questionary_items
  resources :questionaries
  
  get 'questionary_results/calc/:id', to: 'questionary_results#calc'
  get 'questionary_choices/new/:id', to: 'questionary_choices#new'
  get 'questionary_items/new/:id', to: 'questionary_items#new'
  post 'questionaries/:id', to: 'questionaries#sendform'
  
  get 'users/index'
  get 'users/show'
  get 'users/edit'
  get 'communities/index'
  get 'communities/show'
  get 'communities/new'
  get 'communities/edit'

root to: 'homes#top'

devise_for :admins, controllers: {
sessions:      'admins/sessions',
passwords:     'admins/passwords',
registrations: 'admins/registrations'
}
get "communities/belonged" => "communities#belonged"

namespace :admins do
 resources :users, :only => [:show]
 resources :communities do
  resources :posts do
   resources :post_comments, only: [:show, :index]
  end
 end
end

devise_for :users, controllers: {
  sessions:      'users/sessions',
  passwords:     'users/passwords',
  registrations: 'users/registrations'
}
namespace :users do
resources :users ,:only => [:show, :edit,:update]  
get '/search', to: 'search#search'
resources :communities, :only => [:index,:show] do
 resource :belongs, only: [:create, :destroy]
 resources :posts, :only => [:index,:show] do
   resources :post_comments, only: [:create, :destroy]
 end
end
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

communitycommit/app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
has_many :communities, dependent: :destroy 
has_many :posts, dependent: :destroy

end

communitycommit/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

communitycommit/app/models/belong.rb
class Belong < ApplicationRecord
    
belongs_to :user
belongs_to :community
    
end

communitycommit/app/models/community.rb
class Community < ApplicationRecord
    
belongs_to :admin
has_many :posts, dependent: :destroy
has_many :belongs, dependent: :destroy
has_many :questionaries, dependent: :destroy
   
  validates :name, presence: true
   
  def belonged_by?(user)
    belongs.where(user_id: user.id).exists?
  end

  def self.search_for(content, method)
    if method == 'perfect'
      Community.where(name: content)
    else
      Community.where('name LIKE ?', '%'+content+'%')
    end
  end

end

communitycommit/app/models/post.rb
class Post < ApplicationRecord
    
belongs_to :admin
belongs_to :community
has_many :post_comments, dependent: :destroy

validates :title, presence: true
validates :in_front, inclusion: { in: [true, false] }
attachment :image

end

communitycommit/app/models/post_comment.rb
class PostComment < ApplicationRecord
    
  belongs_to :user
  belongs_to :post

end

communitycommit/app/models/questionary.rb
class Questionary < ApplicationRecord
    
belongs_to :community
has_many :questionary_item
has_many :questionary_result

validates :title, :description, :deadline, presence: {message:"は、必須項目です。"}
    
end

communitycommit/app/models/questionary_choice.rb
class QuestionaryChoice < ApplicationRecord
    

belongs_to :questionary_item

validates :content, :value, presence: {message:"は、必須項目です。"}
validates :value, numericality: {message:"は、数字で入力してください。"}        
    
end

communitycommit/app/models/questionary_item.rb
class QuestionaryItem < ApplicationRecord
    

belongs_to :questionary
has_many :questionary_choice

validates :content, presence: {message:"は、必須項目です。"}
    
end

communitycommit/app/models/questionary_result.rb
class QuestionaryResult < ApplicationRecord
    

belongs_to :questionary

validates:result, presence: {message:"は、必須項目です。"}

end

communitycommit/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  validates :name, presence: true
  validates :email, presence: true

  has_many :communities
  has_many :post_comments, dependent: :destroy
  has_many :belongs, dependent: :destroy
end

communitycommit/app/controllers/homes_controller.rb
class HomesController < ApplicationController

def top
end

end

communitycommit/app/helpers/application_helper.rb
module ApplicationHelper
end

communitycommit/app/helpers/belongs_helper.rb
module BelongsHelper
end

communitycommit/app/helpers/communities_helper.rb
module CommunitiesHelper
end

communitycommit/app/helpers/homes_helper.rb
module HomesHelper
end

communitycommit/app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

communitycommit/app/helpers/post_helper.rb
module PostHelper
end

communitycommit/app/helpers/search_helper.rb
module SearchHelper
end

communitycommit/app/helpers/users_helper.rb
module UsersHelper
end

communitycommit/app/views/layouts/_search.html.erb
<div class="search-form">
  <%= form_with url: users_search_path, method: :get, local: true do |f| %>
    <%= f.text_field :content, :class => 'form-control', :placeholder => "コミュニティ名" %>
    <%= f.select :method, options_for_select({ "完全一致検索" => "perfect", "部分検索" => "partial" }) %>
    <%= f.submit '検索', class: 'btn btn-info' %>
  <% end %>
</div>

communitycommit/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Communitycommit</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
   <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
<body class="jumbotron jumbotron-fluid" style="background: url(<%= asset_path "background-sky.jpg" %>); background-size:content; background-attachment:fixed; ">
 
<header>
　　<nav class="navbar navbar-expand-sm">
    
        <div class="collapse navbar-collapse justify-content-center">
              <a href="/"><%= image_tag 'logo.l.png', size: '160x110', class: "navbar-brand logo justify-content-left", alt: "ヘッダーロゴ" %></a>　　          
            <ul class="navbar-nav">
        <% if user_signed_in? %>
          <li class="nav-item active"><%= link_to "トップ", root_path, class: 'btn btn-info btn-lg mr-4' %></li>        
          <li class="nav-item active"><%= link_to "マイページ",users_user_path(current_user.id), class: 'btn btn-info btn-lg mr-4' %></li> 
          <li class="nav-item active"><%= link_to "コミュニティ一覧",users_communities_path, class: 'btn btn-info btn-lg mr-4' %></li> 
          <li class="nav-item active"><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn btn-info btn-lg mr-4' %></li>
          <li class="nav-item active"><%= render 'layouts/search' %></li>
        <% elsif admin_signed_in? %>
          <li class="nav-item active"><%= link_to "トップ", root_path, class: 'btn btn-info btn-lg mr-4' %></li> 
          <li class="nav-item active"><%= link_to "コミュニティ一覧", admins_communities_path, class: 'btn btn-info btn-lg mr-4' %></li> 
          <li class="nav-item active"><%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'btn btn-info btn-lg' %></li>
          <h3 class="nav-item text-warning ml-5"><strong>管理者としてログイン中<strong></h3>
        <% else %> 
         <div class = "text-center text-light">
         <h1 class="fw-lighter"> CommunityCommit</h1>
         <h3><strong>コミュニティコミット</strong></h3></div>  
        <% end %>
       </ul>
    </nav>
 </div>
</header> 

 <div class="container pt-3 pb-3 pl-3 pr-3">
    <% if flash[:notice] %>
      <p><%= flash[:notice] %></p>
    <% end %>
    
    <%= yield %>
 </div>
 

<footer class = "mt-5">
 <div class = "text-center text-primary"> <a href="mailto:comcom@example.com?subject=コミコミお問い合わせ">お問い合わせ</a></div>  
 <%= link_to root_path do %>
 <div class = "text-center text-primary"><h3>CommunityCommit</h3></div>
  <% end %> 
</footer>

</body>
</html>