communitycommit/config/routes.rb
Rails.application.routes.draw do

  resources :questionary_results
  resources :questionary_choices
  resources :questionary_items
  resources :questionaries
  
  get 'questionary_results/calc/:id', to: 'questionary_results#calc'
  get 'questionary_choices/new/:id', to: 'questionary_choices#new'
  get 'questionary_items/new/:id', to: 'questionary_items#new'
  post 'questionaries/:id', to: 'questionaries#sendform'
  
  get 'users/index'
  get 'users/show'
  get 'users/edit'
  get 'communities/index'
  get 'communities/show'
  get 'communities/new'
  get 'communities/edit'

root to: 'homes#top'

devise_for :admins, controllers: {
sessions:      'admins/sessions',
passwords:     'admins/passwords',
registrations: 'admins/registrations'
}
get "communities/belonged" => "communities#belonged"

namespace :admins do
 resources :users, :only => [:show]
 resources :communities do
  resources :posts do
   resources :post_comments, only: [:show, :index]
  end
 end
end

devise_for :users, controllers: {
  sessions:      'users/sessions',
  passwords:     'users/passwords',
  registrations: 'users/registrations'
}
namespace :users do
resources :users ,:only => [:show, :edit,:update]  
get '/search', to: 'search#search'
resources :communities, :only => [:index,:show] do
 resource :belongs, only: [:create, :destroy]
 resources :posts, :only => [:index,:show] do
   resources :post_comments, only: [:create, :destroy]
 end
end
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

communitycommit/app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
has_many :communities, dependent: :destroy 
has_many :posts, dependent: :destroy

end

communitycommit/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

communitycommit/app/models/belong.rb
class Belong < ApplicationRecord
    
belongs_to :user
belongs_to :community
    
end

communitycommit/app/models/community.rb
class Community < ApplicationRecord
    
belongs_to :admin
has_many :posts, dependent: :destroy
has_many :belongs, dependent: :destroy
has_many :questionaries, dependent: :destroy
   
  validates :name, presence: true
   
  def belonged_by?(user)
    belongs.where(user_id: user.id).exists?
  end

  def self.search_for(content, method)
    if method == 'perfect'
      Community.where(name: content)
    else
      Community.where('name LIKE ?', '%'+content+'%')
    end
  end

end

communitycommit/app/models/post.rb
class Post < ApplicationRecord
    
belongs_to :admin
belongs_to :community
has_many :post_comments, dependent: :destroy

validates :title, presence: true
validates :in_front, inclusion: { in: [true, false] }
attachment :image

end

communitycommit/app/models/post_comment.rb
class PostComment < ApplicationRecord
    
  belongs_to :user
  belongs_to :post

end

communitycommit/app/models/questionary.rb
class Questionary < ApplicationRecord
    
belongs_to :community
has_many :questionary_item
has_many :questionary_result

validates :title, :description, :deadline, presence: {message:"は、必須項目です。"}
    
end

communitycommit/app/models/questionary_choice.rb
class QuestionaryChoice < ApplicationRecord
    

belongs_to :questionary_item

validates :content, :value, presence: {message:"は、必須項目です。"}
validates :value, numericality: {message:"は、数字で入力してください。"}        
    
end

communitycommit/app/models/questionary_item.rb
class QuestionaryItem < ApplicationRecord
    

belongs_to :questionary
has_many :questionary_choice

validates :content, presence: {message:"は、必須項目です。"}
    
end

communitycommit/app/models/questionary_result.rb
class QuestionaryResult < ApplicationRecord
    

belongs_to :questionary

validates:result, presence: {message:"は、必須項目です。"}

end

communitycommit/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  validates :name, presence: true
  validates :email, presence: true

  has_many :communities
  has_many :post_comments, dependent: :destroy
  has_many :belongs, dependent: :destroy
end

communitycommit/app/controllers/homes_controller.rb
class HomesController < ApplicationController

def top
end

end

communitycommit/app/helpers/application_helper.rb
module ApplicationHelper
end

communitycommit/app/helpers/belongs_helper.rb
module BelongsHelper
end

communitycommit/app/helpers/communities_helper.rb
module CommunitiesHelper
end

communitycommit/app/helpers/homes_helper.rb
module HomesHelper
end

communitycommit/app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

communitycommit/app/helpers/post_helper.rb
module PostHelper
end

communitycommit/app/helpers/questionaries_helper.rb
module QuestionariesHelper
end

communitycommit/app/helpers/questionary_items_helper.rb
module QuestionaryItemsHelper
end

communitycommit/app/helpers/search_helper.rb
module SearchHelper
end

communitycommit/app/helpers/users_helper.rb
module UsersHelper
end

communitycommit/app/views/homes/top.html.erb
<div class="row">
 <div class="col-12">  
　<div class="jumbotron" style="background: url(<%= asset_path "top1.jpg" %>) bottom; background-size:cover;"> 
   <div>
    <h3 class="display-4 text-white">小さなコミュニティに大きな関心を</h3>
    <p class="lead text-white"><strong>コミュニティコミットへようこそ</strong></p>
   </div>
  </div> 
 </div>
</div> 

<div class="row">
 <div class="col-12">  
  <div class="main-text text-center border-bottom border-info mb-3 pb-2">
  <h5>
    <strong>このサイトは、マンション管理組合の運営を支援する掲示板サイトです。</br>
    お知らせやアンケートを掲示することで、円滑なマンションライフをサポートいたします。</br>
    ご使用方法は、本ページ下記にてご確認ください。</strong>
   </h5>
  </div>
 </div>
</div>
  
<div class ="row mb-5">
 <% if user_signed_in? %>
 <div class="col-6">
   <h4 class="text-left mt-3"><strong>一般ユーザー（お知らせ等の確認のみ）</strong></h4>
    <%= link_to "ログイン中です", users_user_path(current_user.id), class: 'btn btn-primary btn-lg mb-2' %>
 </div> 
 <% elsif admin_signed_in? %>
 <div class="col-6">
  <h4 class="text-left mt-3"><strong>管理者（コミュニティ代表）</strong></h4>
    <%= link_to "新規登録（管理者）", new_admin_registration_path, class: 'btn btn-warning btn-lg mb-2' %>
    <%= link_to "ログイン（管理者）", new_admin_session_path, class: 'btn btn-warning btn-lg mb-2' %>
  </div>
  <% elsif %>
  <div class="col-6">
  <h4 class="text-left mt-3"><strong>一般ユーザー（お知らせ等の確認のみ）</strong></h4>
    <%= link_to "新規登録（ユーザー）", new_user_registration_path, class: 'btn btn-primary btn-lg mb-2' %>
    <%= link_to "ログイン（ユーザー）", new_user_session_path, class: 'btn btn-primary btn-lg mb-2' %>
  </div>
  <div class="col-6">
  <h4 class="text-left mt-3"><strong>管理者（コミュニティ代表）</strong></h4>
    <%= link_to "新規登録（管理者）", new_admin_registration_path, class: 'btn btn-warning btn-lg mb-2' %>
    <%= link_to "ログイン（管理者）", new_admin_session_path, class: 'btn btn-warning btn-lg mb-2' %>
  </div>
  <% end %>
</div> 
 
 <div class="row">
  <div class="cal-12">
   <div class="jumbotron mb-3" style="background: url(<%= asset_path "glass.jpg" %>) top; background-size:cover">  
    <h3 class="text-left text-white"><strong>ご登録について</strong></h3>
   </div>

  <div class="main-text ml-4  border-bottom border-info mb-3 pb-2">
    <h5><strong>
      このサイトは、管理者が『コミュニティ』を作成し、</br>
    一般ユーザーがその『コミュニティ』に所属することで、情報の共有を図れる掲示板です。</br>
    </br>
    マンション管理組合の理事長様や、マンション管理会社の担当フロント様が、</br>
    本サイトでは『管理者』として、ご登録いただき、『コミュニティ』を作成してください。</br>
    <% if user_signed_in? %>
    <% elsif admin_signed_in? %>
    <% elsif %> 
    <%= link_to "新規登録（管理者）", new_admin_registration_path, class: 'btn btn-warning btn-block mt-4' %></br>
    <% end %> 
    そのほかの方は、『一般ユーザー』として、ご登録いただき、</br>
    『管理者』が作成した『コミュニティ』ページにて、『所属』ボタンを押し、所属してください。</br>
    それ以降は、一般ユーザー様は、マイページから、所属しているコミュニティを確認できます。</br>
    <% if user_signed_in? %>
    <% elsif admin_signed_in? %>
    <% elsif %>    
    <%= link_to "新規登録（一般ユーザー）", new_user_registration_path, class: 'btn btn-primary btn-block mt-4 mb-5' %>
    <% end %>
    </strong></h5> 
  </div>
  
 <div class="jumbotron mt-5" style="background: url(<%= asset_path "flower.jpg" %>) center; background-size:cover">   
  <h3 class="text-left"><strong>登録後のご利用可能機能について</strong></h3>
 </div> 
  
  <div class="main-text ml-4">
   <h5><strong>
    管理者様は、コミュニティを作成後、そのコミュニティにて『お知らせ』を作成できます。</br>
    そのお知らせはコミュニティごとのページに掲載されます。</br>
    お知らせ作成の際に、重要度を『高』に設定いただくと、そのコミュニティページトップに掲載します。</br>
    重要度を『低』とした場合はお知らせ一覧のみの掲載となります。</br>
    コミュニティページトップのお知らせは、新しいお知らせから順番に10個まで掲示されます。</br>
　　ページトップ掲載が10個を超えた場合、投稿時間が古い順に消えますが、お知らせ一覧には掲載がなされています。</br>
    アンケートの場合は、新しいものから5個までが掲示されますが、5個を超えた場合、</br>
　　古いアンケートから消えるため、ご注意ください。
   </strong></h5> 
   
   <h5><strong>
    一般ユーザー様は、所属したコミュニティのお知らせをコミュニティページの
    お知らせ掲示板にて確認することができます。また、ユーザー様は各お知らせにコメントをすることや、
    アンケートに回答することができます。
   </strong></h5>
   </div>

 </div> 
</div>

<div class ="row mt-3">
 <div class="col-5 ml-5 ">
  <%= image_tag 'postnew.png', size: '400x300', style: 'background-image'%>
  <div><h5 class="text-center mt-1"><strong>簡単にお知らせを作成して…、</strong></h5></div>
 </div> 
 
 <div class="col-5">
 <%= image_tag 'post.png', size: '400x300', style: 'background-image'%>
  <div><h5 class="text-center mt-1"><strong>簡単にみんなに通知しましょう！！</strong></h5></div> 
  
  <div class="text-center border-bottom border-info mb-3 pb-2">
   <h5><strong>本サイトをご利用にあたってのご意見やご質問は</br>
    サイト下部「お問い合わせ」より、メールにてお寄せください。</strong></h5>
  </div>  
  
 </div> 
</div>  