communitycommit/config/routes.rb
Rails.application.routes.draw do

  resources :questionary_results
  resources :questionary_choices
  resources :questionary_items
  resources :questionaries
  
  get 'questionary_results/calc/:id', to: 'questionary_results#calc'
  get 'questionary_choices/new/:id', to: 'questionary_choices#new'
  get 'questionary_items/new/:id', to: 'questionary_items#new'
  post 'questionaries/:id', to: 'questionaries#sendform'
  
  get 'users/index'
  get 'users/show'
  get 'users/edit'
  get 'communities/index'
  get 'communities/show'
  get 'communities/new'
  get 'communities/edit'

root to: 'homes#top'

devise_for :admins, controllers: {
sessions:      'admins/sessions',
passwords:     'admins/passwords',
registrations: 'admins/registrations'
}
get "communities/belonged" => "communities#belonged"

namespace :admins do
 resources :users, :only => [:show]
 resources :communities do
  resources :posts do
   resources :post_comments, only: [:show, :index]
  end
 end
end

devise_for :users, controllers: {
  sessions:      'users/sessions',
  passwords:     'users/passwords',
  registrations: 'users/registrations'
}
namespace :users do
resources :users ,:only => [:show, :edit,:update]  
get '/search', to: 'search#search'
resources :communities, :only => [:index,:show] do
 resource :belongs, only: [:create, :destroy]
 resources :posts, :only => [:index,:show] do
   resources :post_comments, only: [:create, :destroy]
 end
end
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

communitycommit/app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
has_many :communities, dependent: :destroy 
has_many :posts, dependent: :destroy

end

communitycommit/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

communitycommit/app/models/belong.rb
class Belong < ApplicationRecord
    
belongs_to :user
belongs_to :community
    
end

communitycommit/app/models/community.rb
class Community < ApplicationRecord
    
belongs_to :admin
has_many :posts, dependent: :destroy
has_many :belongs, dependent: :destroy
has_many :questionaries, dependent: :destroy
   
  validates :name, presence: true
   
  def belonged_by?(user)
    belongs.where(user_id: user.id).exists?
  end

  def self.search_for(content, method)
    if method == 'perfect'
      Community.where(name: content)
    else
      Community.where('name LIKE ?', '%'+content+'%')
    end
  end

end

communitycommit/app/models/post.rb
class Post < ApplicationRecord
    
belongs_to :admin
belongs_to :community
has_many :post_comments, dependent: :destroy

validates :title, presence: true
validates :in_front, inclusion: { in: [true, false] }
attachment :image

end

communitycommit/app/models/post_comment.rb
class PostComment < ApplicationRecord
    
  belongs_to :user
  belongs_to :post

end

communitycommit/app/models/questionary.rb
class Questionary < ApplicationRecord
    
belongs_to :community
has_many :questionary_item
has_many :questionary_result

validates :title, :description, :deadline, presence: {message:"は、必須項目です。"}
    
end

communitycommit/app/models/questionary_choice.rb
class QuestionaryChoice < ApplicationRecord
    

belongs_to :questionary_item

validates :content, :value, presence: {message:"は、必須項目です。"}
validates :value, numericality: {message:"は、数字で入力してください。"}        
    
end

communitycommit/app/models/questionary_item.rb
class QuestionaryItem < ApplicationRecord
    

belongs_to :questionary
has_many :questionary_choice

validates :content, presence: {message:"は、必須項目です。"}
    
end

communitycommit/app/models/questionary_result.rb
class QuestionaryResult < ApplicationRecord
    

belongs_to :questionary

validates:result, presence: {message:"は、必須項目です。"}

end

communitycommit/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  validates :name, presence: true
  validates :email, presence: true

  has_many :communities
  has_many :post_comments, dependent: :destroy
  has_many :belongs, dependent: :destroy
end

communitycommit/app/controllers/admins/communities_controller.rb
class Admins::CommunitiesController < ApplicationController
    before_action :authenticate_admin!
    
  def index
  @communities = Community.page(params[:page]).per(20)  
  end

  def show
    @community = Community.find(params[:id])
    @posts = Community.find(params[:id]).posts.page(params[:page]).per(10)  
    @questionaries = Questionary.page(params[:page]).per(5)    
  end

  def new
    @community = Community.new
  end

  def create
    @community = Community.new(community_params)
    @community.admin_id = current_admin.id
    if @community.save
      redirect_to admins_communities_path
    else
     flash[:notice] = "※コミュニティ名を入れてください"
     render 'new'
    end
  end

  def edit
    @community = Community.find(params[:id])
  end

  def update
    @community = Community.find(params[:id])
    
    if @community.update(community_params)
    redirect_to admins_community_path(@community)
    else
     flash[:notice] = "※コミュニティ名を入れてください"
     render 'edit'
    end
  end

  private
  def community_params
    params.require(:community).permit(:name, :introduction)
  end


end

communitycommit/app/controllers/homes_controller.rb
class HomesController < ApplicationController

def top
end

end

communitycommit/app/controllers/users/communities_controller.rb
class Users::CommunitiesController < ApplicationController
  before_action :authenticate_user!
  def index
  @communities = Community.page(params[:page]).per(20)
  end

  def show
    @community = Community.find(params[:id])
    @posts = Community.find(params[:id]).posts.page(params[:page]).reverse_order.per(10)
    @questionaries = Questionary.page(params[:page]).reverse_order.per(5)
  end
  
  def search
    #Viewのformで取得したパラメータをモデルに渡す
    @communities = Community.search(params[:search])
  end
  
  private
  def community_params
    params.require(:community).permit(:name, :introduction)
  end
end

communitycommit/app/helpers/application_helper.rb
module ApplicationHelper
end

communitycommit/app/helpers/belongs_helper.rb
module BelongsHelper
end

communitycommit/app/helpers/communities_helper.rb
module CommunitiesHelper
end

communitycommit/app/helpers/homes_helper.rb
module HomesHelper
end

communitycommit/app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

communitycommit/app/helpers/post_helper.rb
module PostHelper
end

communitycommit/app/helpers/questionaries_helper.rb
module QuestionariesHelper
end

communitycommit/app/helpers/questionary_items_helper.rb
module QuestionaryItemsHelper
end

communitycommit/app/helpers/search_helper.rb
module SearchHelper
end

communitycommit/app/helpers/users_helper.rb
module UsersHelper
end

communitycommit/app/views/admins/communities/edit.html.erb
<% if @community.admin == current_admin %>
<div class="row">
  <div class="col">
     <h3><strong>コミュニティ編集</strong></h3>

 <%= form_with model: @community, url: admins_community_path, local: true do |f| %>
   <div class="form-group">
     <%= f.label :name, "コミュニティ名" %>
  　  <%= f.text_field :name, class: 'form-control'%>
    </div>
    <div class="form-group">
      <%= f.label :introduction, '概要説明' %>
      <%= f.text_area :introduction, size:"90x5", class: 'form-control' %>
    </div>
    <div class="form-group text-center">
      <%= f.submit '変更を保存',class: 'btn btn-success' %>
     </div>
  <% end %>
        
　</div>
</div>
 <% else %>
 
 <div class = "text-center">
 <h3><strong>あなたが作成したコミュニティではありません</strong></h3></div>  
 
 <% end %> 

communitycommit/app/views/admins/communities/index.html.erb
<div class="row">
  <div class="col">
   <h3 class="text-center"><strong>コミュニティ　一覧ページ</strong></h3>
   <div class="mb-4">
   <h4 class="text-center"> あなたが作成したコミュニティのみが表示されます。</br>
    『新規コミュニティ作成』ボタンを押して、コミュニティを作成してください。
   </h4>
   </div>
   
  </div>
 </div>

 <table class="table table-hover bg-light">
   <thead>
    <tr>
     <th>コミュニティID</th>
     <th>コミュニティ名</th>
     <th></th>
    </tr>
   </thead>
 <% @communities.each do |community| %>
   <% if community.admin == current_admin %> 
   <tbody>
    <tr>
     <td> <%= community.id %></td>
     <td>
    　 <%= link_to admins_community_path(community.id) do %>
       <%= community.name %>
      <% end %>
     </td>
     <td>
    　 <%= link_to "詳細ページ",admins_community_path(community.id), class: 'btn btn-info' %></td>
    </tr>
   </tbody>
   <% end %>
  <% end %> 
  </table>
    <%= link_to "新規コミュニティ作成", new_admins_community_path, class: 'btn btn-success btn-lg btn-block' %>
    
   <%= paginate @communities %>
 </div>
</div>

communitycommit/app/views/admins/communities/new.html.erb
<div class="row">
  <div class="col">
      <h3><strong>新規登録</strong></h3>

  <div class="mx-auto">
        <%= form_with model: @community, url: admins_communities_path, local:true do |f| %>
        <div class="form-group">
          <%= f.label :name, "コミュニティ名" %>
          <%= f.text_field :name, class: 'form-control'%>
        </div>
        <div class="form-group">
          <%= f.label :introduction, '概要説明' %>
          <%= f.text_area :introduction, size:"90x5", class: 'form-control' %>
        </div>
        <div class="form-group text-center">
          <%= f.submit "新規登録", class: "btn btn-success btn-block" %>
        </div>
        <% end %>
    </div>
  </div>
</div>

communitycommit/app/views/admins/communities/show.html.erb
<% if @community.admin == current_admin %>
<div class="row">
  <div class="col-md-5">
    <h2 class="text-center mb-5"><strong><%= @community.name %>ページ</strong></h2>
  </div>
</div>
 
<div class="row border-bottom border-info">
 <div class="col">
 <h5><strong>登録情報</strong></h5>
   <table class="table table-bordered bg-light">
    <tbody>
      <tr>
       <th>コミュニティ名</th>
       <td><%= @community.name %></td>
       </tr>
       <tr>
        <th>概要説明</th>
        <td><%= @community.introduction %></td>
       </tr>
      </tbody>
    </table>
     <%= link_to "編集する", edit_admins_community_path(@community), class: "btn btn-success btn-block mb-3" %>
 </div>
</div>

<div class="row mt-5 border-bottom border-info">
 <div class="col">
   <h5><strong>お知らせ掲示板</strong><%= link_to "全てを表示", admins_community_posts_path(@community), class: "btn btn-success ml-2" %></h5>
   <table class="table table-bordered">
  　　<thead>
   　 <tr class="bg-light">
      <th>タイトル</th>
      <th>掲載日</th>
      <th colspan="2"></th>
　　 </tr>
 　  </thead>    
    <tbody>
     <% @posts.each do |post| %>
     <% if post.in_front == true %>
     <tr class="bg-light"> 
     <td><%= link_to  admins_community_post_path(community_id: post.community_id, id: post.id)  do %><%= post.title %><% end %></td>
     <td><%= post.created_at.in_time_zone('Tokyo').strftime('%Y/%m/%d %H:%M:%S') %></td>
     <td><%= link_to "編集する", edit_admins_community_post_path(post), class: "btn btn-success" %></td>
     <td><%= link_to "削除する", admins_community_post_path(community_id: post.community_id, id: post.id), method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn btn-danger destroy_book_#{post.id}" %></td> 
      </tr>
      <% end %> 
     <% end %>     
     </tbody>
    </table>
    
 <%= link_to "お知らせ作成", new_admins_community_post_path(@community), class: "btn btn-success btn-block mb-3" %>
  </div>
 </div>

<div class="row mt-5">
 <div class="col">
  <h5><strong>アンケート</strong></h5>
<table class="table table-bordered">
  <thead>
    <tr class="bg-light">
      <th>タイトル</th>
      <th>締め切り日</th>
      <th colspan="2"></th>
    </tr>
  </thead>
  <tbody>
    <% @questionaries.each do |questionary| %>
      <tr class="bg-light">
       <% if questionary.community_id == @community.id %>
        <td><%= questionary.title %></td>
        <td><%= questionary.deadline %></td>
        <td><%= link_to '詳細確認', questionary, class: "btn btn-success" %></td>
        <td><%= link_to '削除する', questionary, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
      <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'アンケート作成', new_questionary_path, class: "btn btn-success btn-block" %>
  </div>
 </div>

 <div class="row mt-5">
  <div class="col-9">
   <div class="panel-group mt-3" id="accordion">
    <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <strong>所属人数<%= @community.belongs.count %>人</strong>  
        <a data-toggle="collapse" data-parent="#accordion" href="#collapse3">▼</a>
      </h4>
    </div>
    <div id="collapse3" class="panel-collapse collapse in">
      <div class="panel-body bg-light">
        <% @community.belongs.each do |community| %>    
        <h5 class="ml-3"><%= link_to admins_user_path(id: community.user.id) do %><%= community.user.name %><% end %></h5>
        <% end %>
     </div>
    </div>
  </div>
 </div> 
</div>
</div>
 <% else %>
 
<div class="row">
  <div class="col">
   <div class = "text-center">
    <h3><strong>あなたが作成したコミュニティではありません</strong></h3>
   </div>  
 </div> 
</div> 

 <% end %> 